DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;


CREATE TABLE IF NOT EXISTS ADDRESS
(
  addrId  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  street  VARCHAR(255)             DEFAULT NULL,
  city    VARCHAR(255)             DEFAULT NULL,
  state   VARCHAR(255)             DEFAULT NULL,
  zip     VARCHAR(255)             DEFAULT NULL,
  country VARCHAR(255)             DEFAULT NULL
)
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS USER
(
  userName           VARCHAR(15) PRIMARY KEY NOT NULL,
  passWord           VARCHAR(255)            NOT NULL,
  accountExpired     BIT(1) DEFAULT 0,
  locked             BIT(1) DEFAULT 0,
  credentialsExpired BIT(1) DEFAULT 0,
  addrId             INT    DEFAULT NULL,
  FOREIGN KEY (addrId) REFERENCES ADDRESS (addrId)
)
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS ROLE
(
  roleName VARCHAR(15) NOT NULL PRIMARY KEY
)
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS USER_ROLE
(
  id       INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userName VARCHAR(15) NOT NULL,
  FOREIGN KEY (userName) REFERENCES USER (userName),
  roleName VARCHAR(15) NOT NULL,
  FOREIGN KEY (roleName) REFERENCES ROLE (roleName)
)
  DEFAULT CHARSET = utf8;
