DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;

CREATE TABLE IF NOT EXISTS USER
(
	userName VARCHAR(15) PRIMARY KEY NOT NULL,
	passWord VARCHAR(255) NOT NULL,
	accountExpired BIT(1) DEFAULT 0,
	locked BIT(1) DEFAULT 0,
	credentialsExpired BIT(1) DEFAULT 0
) DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS ROLE
(
	roleName varchar(15) NOT NULL PRIMARY KEY
) DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS USER_ROLE
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userName VARCHAR(15) NOT NULL,
	FOREIGN KEY (userName) REFERENCES USER(userName),
	roleName VARCHAR(15) NOT NULL,
	FOREIGN KEY (roleName) REFERENCES ROLE(roleName)
) DEFAULT CHARSET = utf8;
